version: '3.8'

services:
  hedge-engine:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: xlp-hedge-engine
    restart: unless-stopped

    # 持久化存储
    volumes:
      # 指标导出持久化（可选）
      - ../logs:/app/logs

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # 健康检查（检查主进程是否运行）
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*main.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  # 可选：监控服务（未来扩展）
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: xlp-prometheus
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus-data:/prometheus
  #   ports:
  #     - "9090:9090"

# volumes:
#   prometheus-data:
